# Generated by Django 3.2 on 2021-10-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_alter_shorturl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
